### PR TITLE
Update v8.1.1

### PR DESCRIPTION
**Pull request by ejullo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ejullo** [comment]
@conda-forge-admin, please rerender

**Comment by ejullo** [comment]
@conda-forge-admin, please rerender

**Comment by ejullo** [comment]
@conda-forge-admin, please merge

**Comment by ejullo** [comment]
@xhochy, can you merge this PR? I don't have the right to do it. Thanks!

**Comment by xhochy** [comment]
@ejullo You should have the rights here, maybe your conda-forge invite timeouted?

@conda-forge-admin please update team

**Comment by ejullo** [comment]
@xhochy yes, it seems that the invitation timeouted. Is there a way to regenerate an invitation?

**Pull request merged**
